version: "3.9"

services:
  db:
    image: postgres:15
    container_name: recruitment_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruitment_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
    environment:
      ENV_FILE: .env.prod
volumes:
  db_data:
networks:
  backend:
