version: "3.9"

services:
  db:
    image: postgres:15
    container_name: recruitment_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "54320:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruitment_api
    restart: always
    ports:
      - "8000:8000"  # API доступен на http://localhost:8000
    depends_on:
      - db
    networks:
      - backend
    environment:
      DB_HOST: db  # Указываем имя сервиса базы данных
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    volumes:
      - .:/code  # Монтируем локальную папку проекта внутрь контейнера
    command: >
      bash -c "python app/db/init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  db_data:

networks:
  backend:
